import './js/year-of-birth';
import'./js/guess-number';
import './js/paper';
import './js/our-team';
import './js/our-team';
import './js/bigger-number';
import './js/bigger-number';
import './js/footer-modal';
import './js/dino';
import './js/football';
import'./js/scintists';
import './js/calculator';
import './js/time-calculator';
import './js/dropdown';
// import './js/dino';
