import './js/year-of-birth';
import'./js/guess-number';
import './js/paper';
import './js/our-team';
import './js/our-team';
import './js/bigger-number';
import './js/bigger-number';
import './js/calculator-js';
import './js/calculator';
import './js/dino';
